// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwmxlwnkwxcsxosqjmrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3bXhsd25rd3hjc3hvc3FqbXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODY2NDUsImV4cCI6MjA2MjU2MjY0NX0.JnzNmPosLdcuxQhf5gk2lITjP6FiKnCljJu6n6oc3yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);